<link rel="import" href="/bower_components/prism-js/prism-js.html">
<template><div class="wikiArticle text-content redesign">
<div>
  <div class="overheadIndicator" style="background: #9CF49C;">
    <p><strong>This is an experimental technology, part of the Harmony (ECMAScript 6) proposal.</strong><br>Because this technology&apos;s specification has not stabilized, check the <a href="#/Promise.prototype.catch()#Browser_compatibility">compatibility table</a> for usage in various browsers. Also note that the syntax and behavior of an experimental technology is subject to change in future version of browsers as the spec changes.</p>
</div></div>
<h2 id="Summary" name="Summary">Summary</h2>
<p>The <strong>catch()</strong> method returns a <code>Promise</code> and deals with rejected cases only. It behaves the same as calling <a href="#/Promise.prototype.then()" title="The then() method returns a Promise. It takes two arguments, both are callback functions for the success and failure cases of the Promise."><code>Promise.prototype.then(undefined, onRejected)</code></a>.</p>
<h2 id="Syntax" name="Syntax">Syntax</h2>
<pre class="syntaxbox"><var>p.catch(onRejected)</var>;
p.catch(function(reason) {
   // rejection
});
</pre>
<h3 id="Parameters">Parameters</h3>
<dl>
 <dt>
  onRejected</dt>
 <dd>
  A <a href="#/Function" title="The Function constructor creates a new Function object. In JavaScript every function is actually a Function object."><code>Function</code></a> called when the <code>Promise</code> is rejected. This function has one argument, the rejection <code>reason</code>.</dd>
</dl>
<h2 id="Description" name="Description">Description</h2>
<p>The <code>catch</code> method can be useful for error handling in your promise composition.</p>
<h2 id="Examples">Examples</h2>
<h3 id="Using_the_catch_method">Using the <code>catch</code> method</h3>
<prism-js language="javascript">var p1 = new Promise(function(resolve, reject) {
  resolve(&quot;Success&quot;);
});
p1.then(function(value) {
  console.log(value); // &quot;Success!&quot;
  throw &quot;oh, no!&quot;;
}).catch(function(e) {
  console.log(e); // &quot;oh, no!&quot;
});
</prism-js>
<h2 id="Specifications">Specifications</h2>
<table class="standard-table">
 <tbody>
  <tr>
   <th scope="col">Specification</th>
   <th scope="col">Status</th>
   <th scope="col">Comment</th>
  </tr>
  <tr>
   <td><a class="external" href="https://github.com/domenic/promises-unwrapping">domenic/promises-unwrapping</a></td>
   <td>Draft</td>
   <td>Standardization work is taking place here.</td>
  </tr>
  <tr>
   <td><a class="external" href="http://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise.prototype.catch" hreflang="en" lang="en">ECMAScript 6 (ECMA-262)<br><small>The definition of &apos;Promise.prototype.catch&apos; in that specification.</small></a></td>
   <td><span class="spec-Draft">Draft</span></td>
   <td>Initial definition in an ECMA standard.</td>
  </tr>
 </tbody>
</table>
<h2 id="See_also">See also</h2>
<ul>
 <li><a href="#/Promise" title="The Promise object is used for deferred and asynchronous computations. A Promise is in one of the three states:"><code>Promise</code></a></li>
 <li><a href="#/Promise.prototype.then()" title="The then() method returns a Promise. It takes two arguments, both are callback functions for the success and failure cases of the Promise."><code>Promise.prototype.then()</code></a></li>
</ul>
<div class="mdnLicenseFooter">This page on MDN: <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch">Promise.prototype.catch()</a>, by Mozilla Contributors.<br>Licensed under the terms of Creative Commons Attribution-ShareAlike.</div>
</div></template>